# Generated by Django 6.0.7 on 2026-09-28 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0003_color_hex_validator'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsBoard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('type', models.CharField(choices=[('value', 'Display value')], default='value', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('aggregation', models.CharField(choices=[('total', 'Total'), ('average', 'Average')], default='total', max_length=10)),
                ('timeframe', models.CharField(choices=[('today', 'Today'), ('yesterday', 'Yesterday'), ('this_week', 'This week'), ('last_week', 'Last week'), ('this_month', 'This month'), ('last_month', 'Last month'), ('this_quarter', 'This quarter'), ('quarter', 'Quarter'), ('this_year', 'This year'), ('year', 'Year'), ('last_days', 'Last X days')], max_length=20)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('days', models.PositiveIntegerField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='analytics.analyticsboard')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_widgets', to='signals.signal')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddConstraint(
            model_name='analyticsboard',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_analytics_board_name_per_user'),
        ),
    ]
