# Generated by Django 6.0.7 on 2026-10-01 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticswidget',
            name='chart_type',
            field=models.CharField(choices=[('bar', 'Bar'), ('line', 'Line')], default='bar', max_length=10),
        ),
        migrations.AddField(
            model_name='analyticswidget',
            name='show_average',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='analyticswidget',
            name='type',
            field=models.CharField(choices=[('value', 'Display value'), ('timeseries', 'Over time')], default='value', max_length=20),
        ),
    ]
