# Generated by Django 6.0.7 on 2026-07-23 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signalcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signal_categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signal',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='signals.signalcategory'),
        ),
        migrations.AddField(
            model_name='signalrangeconfig',
            name='signal',
            field=models.OneToOneField(limit_choices_to={'type': 'range'}, on_delete=django.db.models.deletion.CASCADE, related_name='range_config', to='signals.signal'),
        ),
        migrations.AddField(
            model_name='signalvalueconfig',
            name='signal',
            field=models.OneToOneField(limit_choices_to={'type': 'value'}, on_delete=django.db.models.deletion.CASCADE, related_name='value_config', to='signals.signal'),
        ),
        migrations.AddConstraint(
            model_name='signalcategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='signalrangeconfig',
            constraint=models.CheckConstraint(condition=models.Q(('max_value__gt', models.F('min_value'))), name='range_max_gt_min'),
        ),
    ]
