# Generated by Django 6.0.7 on 2026-07-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signals', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='summary_method',
            field=models.CharField(choices=[('average', 'Average'), ('total', 'Total')], default='total', max_length=10),
        ),
    ]
