# Generated by Django 6.0.6 on 2026-07-06 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trackers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('tracker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tracker', to='trackers.tracker')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrackerBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trackers', models.ManyToManyField(related_name='board', through='boards.BoardTracker', to='trackers.tracker')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boardtracker',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_trackers', to='boards.trackerboard'),
        ),
        migrations.AddConstraint(
            model_name='trackerboard',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_board_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='boardtracker',
            constraint=models.UniqueConstraint(fields=('board', 'tracker'), name='unique_tracker_per_board'),
        ),
    ]
