# Generated by Django 6.0.7 on 2026-07-23 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0001_initial'),
        ('signals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardsignal',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_signal', to='signals.signal'),
        ),
        migrations.AddField(
            model_name='signalboard',
            name='signals',
            field=models.ManyToManyField(related_name='boards', through='boards.BoardSignal', to='signals.signal'),
        ),
    ]
