# Generated by Django 6.0.6 on 2026-07-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
        ('trackers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='boardtracker',
            name='unique_tracker_per_board',
        ),
        migrations.AddConstraint(
            model_name='boardtracker',
            constraint=models.UniqueConstraint(fields=('board', 'tracker'), name='unique_tracker_per_board'),
        ),
    ]
