# Generated by Django 6.0.7 on 2026-08-19 14:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boards', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='signalboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='boardsignal',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_signals', to='boards.signalboard'),
        ),
        migrations.AddConstraint(
            model_name='signalboard',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_board_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='boardsignal',
            constraint=models.UniqueConstraint(fields=('board', 'signal'), name='unique_signal_per_board'),
        ),
    ]
