# Generated by Django 6.0.7 on 2026-07-27 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signalboard',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='signalboard',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boardsignal',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_signals', to='boards.signalboard'),
        ),
    ]
