# Generated by Django 6.0.6 on 2026-07-06 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0003_alter_trackerboard_trackers_alter_trackerboard_user'),
        ('trackers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='trackerboard',
            name='trackers',
            field=models.ManyToManyField(related_name='boards', through='boards.BoardTracker', to='trackers.tracker'),
        ),
        migrations.AlterField(
            model_name='trackerboard',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
    ]
