services:
  db:
    image: postgres:18
    container_name: bitjournal-postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - bitjournal_data:/var/lib/postgresql

volumes:
  bitjournal_data:
