# Generated by Django 6.0.7 on 2026-10-05 10:04

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='bitjournaluser',
            managers=[
                ('objects', apps.users.models.BitjournalUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='bitjournaluser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='bitjournaluser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
