# Generated by Django 6.0.7 on 2026-08-20 09:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signals', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('occurred_at', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='SignalEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid7, editable=False, primary_key=True, serialize=False)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='events.event')),
                ('signal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='signals.signal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='event',
            name='signal',
            field=models.ManyToManyField(related_name='events', through='events.SignalEntry', to='signals.signal'),
        ),
        migrations.AddIndex(
            model_name='signalentry',
            index=models.Index(fields=['signal', 'event'], name='events_sign_signal__07634f_idx'),
        ),
        migrations.AddConstraint(
            model_name='signalentry',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('duration__isnull', True), ('value__isnull', False)), models.Q(('duration__isnull', False), ('value__isnull', True)), _connector='OR'), name='signalentry_exactly_one_of_value_duration'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'occurred_at'], name='events_even_user_id_37084f_idx'),
        ),
    ]
