# Generated by Django 6.0.7 on 2026-09-09 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='signalentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
