# Generated by Django 6.0.7 on 2026-07-23 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('signals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signalentry',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='events.event'),
        ),
        migrations.AddField(
            model_name='signalentry',
            name='signal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='signals.signal'),
        ),
        migrations.AddField(
            model_name='event',
            name='signal',
            field=models.ManyToManyField(related_name='events', through='events.SignalEntry', to='signals.signal'),
        ),
        migrations.AddIndex(
            model_name='signalentry',
            index=models.Index(fields=['signal', 'event'], name='events_sign_signal__07634f_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['user', 'date'], name='events_even_user_id_73ae47_idx'),
        ),
    ]
