# Generated by Django 6.0.6 on 2026-07-06 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracker_categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'tracker categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('tally', 'Tally'), ('range', 'Range'), ('value', 'Value'), ('duration', 'Duration')], max_length=20)),
                ('icon', models.CharField(blank=True, max_length=50)),
                ('color', models.CharField(blank=True, max_length=7)),
                ('summary_method', models.CharField(choices=[('average', 'Average'), ('sum', 'Sum (total)')], default='sum', max_length=10)),
                ('is_archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trackers', to='trackers.trackercategory')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrackerRangeConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('min_label', models.CharField(blank=True, max_length=50)),
                ('max_label', models.CharField(blank=True, max_length=50)),
                ('tracker', models.OneToOneField(limit_choices_to={'type': 'range'}, on_delete=django.db.models.deletion.CASCADE, related_name='range_config', to='trackers.tracker')),
            ],
        ),
        migrations.CreateModel(
            name='TrackerValueConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=20)),
                ('tracker', models.OneToOneField(limit_choices_to={'type': 'value'}, on_delete=django.db.models.deletion.CASCADE, related_name='value_config', to='trackers.tracker')),
            ],
        ),
        migrations.AddConstraint(
            model_name='trackercategory',
            constraint=models.UniqueConstraint(fields=('user', 'name'), name='unique_category_name_per_user'),
        ),
        migrations.AddConstraint(
            model_name='trackerrangeconfig',
            constraint=models.CheckConstraint(condition=models.Q(('max_value__gt', models.F('min_value'))), name='range_max_gt_min'),
        ),
    ]
